const countries = [
  { country: 'Afghanistan', currency: 'AFN', symbol: '؋' },
  { country: 'Albania', currency: 'ALL', symbol: 'L' },
  { country: 'Algeria', currency: 'DZD', symbol: 'دج' },
  { country: 'Andorra', currency: 'EUR', symbol: '€' },
  { country: 'Angola', currency: 'AOA', symbol: 'Kz' },
  { country: 'Antigua and Barbuda', currency: 'XCD', symbol: '$' },
  { country: 'Argentina', currency: 'ARS', symbol: '$' },
  { country: 'Armenia', currency: 'AMD', symbol: '֏' },
  { country: 'Australia', currency: 'AUD', symbol: '$' },
  { country: 'Austria', currency: 'EUR', symbol: '€' },
  { country: 'Azerbaijan', currency: 'AZN', symbol: '₼' },
  { country: 'Bahamas', currency: 'BSD', symbol: '$' },
  { country: 'Bahrain', currency: 'BHD', symbol: '.د.ب' },
  { country: 'Bangladesh', currency: 'BDT', symbol: '৳' },
  { country: 'Barbados', currency: 'BBD', symbol: '$' },
  { country: 'Belarus', currency: 'BYN', symbol: 'Br' },
  { country: 'Belgium', currency: 'EUR', symbol: '€' },
  { country: 'Belize', currency: 'BZD', symbol: '$' },
  { country: 'Benin', currency: 'XOF', symbol: 'CFA' },
  { country: 'Bhutan', currency: 'BTN', symbol: 'Nu.' },
  { country: 'Bolivia', currency: 'BOB', symbol: 'Bs.' },
  { country: 'Bosnia and Herzegovina', currency: 'BAM', symbol: 'KM' },
  { country: 'Botswana', currency: 'BWP', symbol: 'P' },
  { country: 'Brazil', currency: 'BRL', symbol: 'R$' },
  { country: 'Brunei', currency: 'BND', symbol: '$' },
  { country: 'Bulgaria', currency: 'BGN', symbol: 'лв' },
  { country: 'Burkina Faso', currency: 'XOF', symbol: 'CFA' },
  { country: 'Burundi', currency: 'BIF', symbol: 'FBu' },
  { country: 'Cabo Verde', currency: 'CVE', symbol: '$' },
  { country: 'Cambodia', currency: 'KHR', symbol: '៛' },
  { country: 'Cameroon', currency: 'XAF', symbol: 'FCFA' },
  { country: 'Canada', currency: 'CAD', symbol: '$' },
  { country: 'Central African Republic', currency: 'XAF', symbol: 'FCFA' },
  { country: 'Chad', currency: 'XAF', symbol: 'FCFA' },
  { country: 'Chile', currency: 'CLP', symbol: '$' },
  { country: 'China', currency: 'CNY', symbol: '¥' },
  { country: 'Colombia', currency: 'COP', symbol: '$' },
  { country: 'Comoros', currency: 'KMF', symbol: 'CF' },
  { country: 'Congo', currency: 'XAF', symbol: 'FCFA' },
  { country: 'Costa Rica', currency: 'CRC', symbol: '₡' },
  { country: 'Croatia', currency: 'EUR', symbol: '€' },
  { country: 'Cuba', currency: 'CUP', symbol: '$' },
  { country: 'Cyprus', currency: 'EUR', symbol: '€' },
  { country: 'Czechia Republic', currency: 'CZK', symbol: 'Kč' },
  { country: 'Denmark', currency: 'DKK', symbol: 'kr' },
  { country: 'Djibouti', currency: 'DJF', symbol: 'Fdj' },
  { country: 'Dominica', currency: 'XCD', symbol: '$' },
  { country: 'Dominican Republic', currency: 'DOP', symbol: 'RD$' },
  { country: 'Ecuador', currency: 'USD', symbol: '$' },
  { country: 'Egypt', currency: 'EGP', symbol: '£' },
  { country: 'El Salvador', currency: 'USD', symbol: '$' },
  { country: 'Equatorial Guinea', currency: 'XAF', symbol: 'FCFA' },
  { country: 'Eritrea', currency: 'ERN', symbol: 'Nfk' },
  { country: 'Estonia', currency: 'EUR', symbol: '€' },
  { country: 'Eswatini', currency: 'SZL', symbol: 'E' },
  { country: 'Ethiopia', currency: 'ETB', symbol: 'Br' },
  { country: 'Fiji', currency: 'FJD', symbol: '$' },
  { country: 'Finland', currency: 'EUR', symbol: '€' },
  { country: 'France', currency: 'EUR', symbol: '€' },
  { country: 'Gabon', currency: 'XAF', symbol: 'FCFA' },
  { country: 'Gambia', currency: 'GMD', symbol: 'D' },
  { country: 'Georgia', currency: 'GEL', symbol: '₾' },
  { country: 'Germany', currency: 'EUR', symbol: '€' },
  { country: 'Ghana', currency: 'GHS', symbol: '₵' },
  { country: 'Greece', currency: 'EUR', symbol: '€' },
  { country: 'Grenada', currency: 'XCD', symbol: '$' },
  { country: 'Guatemala', currency: 'GTQ', symbol: 'Q' },
  { country: 'Guinea', currency: 'GNF', symbol: 'FG' },
  { country: 'Guinea-Bissau', currency: 'XOF', symbol: 'CFA' },
  { country: 'Guyana', currency: 'GYD', symbol: '$' },
  { country: 'Haiti', currency: 'HTG', symbol: 'G' },
  { country: 'Holy See', currency: 'EUR', symbol: '€' },
  { country: 'Honduras', currency: 'HNL', symbol: 'L' },
  { country: 'Hungary', currency: 'HUF', symbol: 'Ft' },
  { country: 'Iceland', currency: 'ISK', symbol: 'kr' },
  { country: 'India', currency: 'INR', symbol: '₹' },
  { country: 'Indonesia', currency: 'IDR', symbol: 'Rp' },
  { country: 'Iran', currency: 'IRR', symbol: '﷼' },
  { country: 'Iraq', currency: 'IQD', symbol: 'ع.د' },
  { country: 'Ireland', currency: 'EUR', symbol: '€' },
  { country: 'Israel', currency: 'ILS', symbol: '₪' },
  { country: 'Italy', currency: 'EUR', symbol: '€' },
  { country: 'Jamaica', currency: 'JMD', symbol: 'J$' },
  { country: 'Japan', currency: 'JPY', symbol: '¥' },
  { country: 'Jordan', currency: 'JOD', symbol: 'JD' },
  { country: 'Kazakhstan', currency: 'KZT', symbol: '₸' },
  { country: 'Kenya', currency: 'KES', symbol: 'KSh' },
  { country: 'Kiribati', currency: 'AUD', symbol: '$' },
  { country: 'Kuwait', currency: 'KWD', symbol: 'د.ك' },
  { country: 'Kyrgyzstan', currency: 'KGS', symbol: 'лв' },
  { country: 'Laos', currency: 'LAK', symbol: '₭' },
  { country: 'Latvia', currency: 'EUR', symbol: '€' },
  { country: 'Lebanon', currency: 'LBP', symbol: 'ل.ل' },
  { country: 'Lesotho', currency: 'LSL', symbol: 'M' },
  { country: 'Liberia', currency: 'LRD', symbol: '$' },
  { country: 'Libya', currency: 'LYD', symbol: 'ل.د' },
  { country: 'Liechtenstein', currency: 'CHF', symbol: 'Fr.' },
  { country: 'Lithuania', currency: 'EUR', symbol: '€' },
  { country: 'Luxembourg', currency: 'EUR', symbol: '€' },
  { country: 'Madagascar', currency: 'MGA', symbol: 'Ar' },
  { country: 'Malawi', currency: 'MWK', symbol: 'MK' },
  { country: 'Malaysia', currency: 'MYR', symbol: 'RM' },
  { country: 'Maldives', currency: 'MVR', symbol: 'Rf' },
  { country: 'Mali', currency: 'XOF', symbol: 'CFA' },
  { country: 'Malta', currency: 'EUR', symbol: '€' },
  { country: 'Marshall Islands', currency: 'USD', symbol: '$' },
  { country: 'Mauritania', currency: 'MRU', symbol: 'UM' },
  { country: 'Mauritius', currency: 'MUR', symbol: '₨' },
  { country: 'Mexico', currency: 'MXN', symbol: '$' },
  { country: 'Micronesia', currency: 'USD', symbol: '$' },
  { country: 'Moldova', currency: 'MDL', symbol: 'L' },
  { country: 'Monaco', currency: 'EUR', symbol: '€' },
  { country: 'Mongolia', currency: 'MNT', symbol: '₮' },
  { country: 'Montenegro', currency: 'EUR', symbol: '€' },
  { country: 'Morocco', currency: 'MAD', symbol: 'د.م.' },
  { country: 'Mozambique', currency: 'MZN', symbol: 'MT' },
  { country: 'Myanmar (formerly Burma)', currency: 'MMK', symbol: 'K' },
  { country: 'Namibia', currency: 'NAD', symbol: '$' },
  { country: 'Nauru', currency: 'AUD', symbol: '$' },
  { country: 'Nepal', currency: 'NPR', symbol: '₨' },
  { country: 'Netherlands', currency: 'EUR', symbol: '€' },
  { country: 'New Zealand', currency: 'NZD', symbol: '$' },
  { country: 'Nicaragua', currency: 'NIO', symbol: 'C$' },
  { country: 'Niger', currency: 'XOF', symbol: 'CFA' },
  { country: 'Nigeria', currency: 'NGN', symbol: '₦' },
  { country: 'North Korea', currency: 'KPW', symbol: '₩' },
  { country: 'North Macedonia', currency: 'MKD', symbol: 'ден' },
  { country: 'Norway', currency: 'NOK', symbol: 'kr' },
  { country: 'Oman', currency: 'OMR', symbol: 'ر.ع.' },
  { country: 'Pakistan', currency: 'PKR', symbol: '₨' },
  { country: 'Palau', currency: 'USD', symbol: '$' },
  { country: 'Palestine State', currency: 'ILS', symbol: '₪' },
  { country: 'Panama', currency: 'PAB', symbol: 'B/.' },
  { country: 'Papua New Guinea', currency: 'PGK', symbol: 'K' },
  { country: 'Paraguay', currency: 'PYG', symbol: '₲' },
  { country: 'Peru', currency: 'PEN', symbol: 'S/' },
  { country: 'Philippines', currency: 'PHP', symbol: '₱' },
  { country: 'Poland', currency: 'PLN', symbol: 'zł' },
  { country: 'Portugal', currency: 'EUR', symbol: '€' },
  { country: 'Qatar', currency: 'QAR', symbol: 'ر.ق' },
  { country: 'Romania', currency: 'RON', symbol: 'lei' },
  { country: 'Russia', currency: 'RUB', symbol: '₽' },
  { country: 'Rwanda', currency: 'RWF', symbol: 'FRw' },
  { country: 'Saint Kitts and Nevis', currency: 'XCD', symbol: '$' },
  { country: 'Saint Lucia', currency: 'XCD', symbol: '$' },
  { country: 'Saint Vincent and the Grenadines', currency: 'XCD', symbol: '$' },
  { country: 'Samoa', currency: 'WST', symbol: 'T' },
  { country: 'San Marino', currency: 'EUR', symbol: '€' },
  { country: 'Sao Tome and Principe', currency: 'STN', symbol: 'Db' },
  { country: 'Saudi Arabia', currency: 'SAR', symbol: 'ر.س' },
  { country: 'Senegal', currency: 'XOF', symbol: 'CFA' },
  { country: 'Serbia', currency: 'RSD', symbol: 'дин.' },
  { country: 'Seychelles', currency: 'SCR', symbol: '₨' },
  { country: 'Sierra Leone', currency: 'SLL', symbol: 'Le' },
  { country: 'Singapore', currency: 'SGD', symbol: '$' },
  { country: 'Slovakia', currency: 'EUR', symbol: '€' },
  { country: 'Slovenia', currency: 'EUR', symbol: '€' },
  { country: 'Solomon Islands', currency: 'SBD', symbol: '$' },
  { country: 'Somalia', currency: 'SOS', symbol: 'Sh.So.' },
  { country: 'South Africa', currency: 'ZAR', symbol: 'R' },
  { country: 'South Korea', currency: 'KRW', symbol: '₩' },
  { country: 'South Sudan', currency: 'SSP', symbol: '£' },
  { country: 'Spain', currency: 'EUR', symbol: '€' },
  { country: 'Sri Lanka', currency: 'LKR', symbol: 'Rs' },
  { country: 'Sudan', currency: 'SDG', symbol: 'ج.س.' },
  { country: 'Suriname', currency: 'SRD', symbol: '$' },
  { country: 'Sweden', currency: 'SEK', symbol: 'kr' },
  { country: 'Switzerland', currency: 'CHF', symbol: 'Fr.' },
  { country: 'Syria', currency: 'SYP', symbol: '£' },
  { country: 'Tajikistan', currency: 'TJS', symbol: 'ЅМ' },
  { country: 'Tanzania', currency: 'TZS', symbol: 'Sh' },
  { country: 'Thailand', currency: 'THB', symbol: '฿' },
  { country: 'Timor-Leste', currency: 'USD', symbol: '$' },
  { country: 'Togo', currency: 'XOF', symbol: 'CFA' },
  { country: 'Tonga', currency: 'TOP', symbol: 'T$' },
  { country: 'Trinidad and Tobago', currency: 'TTD', symbol: 'TT$' },
  { country: 'Tunisia', currency: 'TND', symbol: 'د.ت' },
  { country: 'Turkey', currency: 'TRY', symbol: '₺' },
  { country: 'Turkmenistan', currency: 'TMT', symbol: 'm' },
  { country: 'Tuvalu', currency: 'AUD', symbol: '$' },
  { country: 'Uganda', currency: 'UGX', symbol: 'USh' },
  { country: 'Ukraine', currency: 'UAH', symbol: '₴' },
  { country: 'United Arab Emirates', currency: 'AED', symbol: 'د.إ' },
  { country: 'United Kingdom', currency: 'GBP', symbol: '£' },
  { country: 'United States', currency: 'USD', symbol: '$' },
  { country: 'Uruguay', currency: 'UYU', symbol: '$U' },
  { country: 'Uzbekistan', currency: 'UZS', symbol: 'soʻm' },
  { country: 'Vanuatu', currency: 'VUV', symbol: 'Vt' },
  { country: 'Venezuela', currency: 'VES', symbol: 'Bs.' },
  { country: 'Vietnam', currency: 'VND', symbol: '₫' },
  { country: 'Yemen', currency: 'YER', symbol: '﷼' },
  { country: 'Zambia', currency: 'ZMW', symbol: 'ZK' },
  { country: 'Zimbabwe', currency: 'ZWL', symbol: '$' },
];

export default countries;